spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:my_market;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
